// AI Control Tower — OpenAPI spec static definition (info/servers/security only).
// Every path/schema entry is generated by swagger-jsdoc from @openapi JSDoc
// blocks above each route handler in routes/**/*.js — see server.js. This
// file only holds the hand-written prose and security scheme declarations
// that swagger-jsdoc can't infer from code.
//
// Adapted from Product-Studio-v9.37.01/proxy/openapi/openapi.yaml's intro
// text — this is now this repo's own copy/source of truth, not a mirror;
// keep the two in sync manually if the /v1 contract changes on either side.

module.exports = {
  openapi: '3.0.3',
  info: {
    title: 'AI Cost Control Tower API',
    version: '1.0.0',
    license: { name: 'Internal use only — not for external distribution' },
    description: `
## Getting started

This API lets an internal HCLTech application write its own AI usage and
outcome events into the same Cost Control Tower tables Product Studio
already uses, so it can be traced, costed, and governed the same way. It
also documents the Settings API this repo's own React app uses.

**Registration is not self-service for the Ingestion API.** Contact the
platform operator to register your app and receive a credential.

**Credential handling.** Your API key is shown exactly once, at issuance
time (via the Settings API's credential issue/rotate endpoints). Move it
into your own team's secrets manager immediately — it is never stored in
plaintext or recoverable after that point. Every Ingestion API request
authenticates with \`Authorization: Bearer <api_key>\`; \`company_id\` and
\`app_id\` are resolved from the credential server-side and are never
accepted as request fields.

\`\`\`bash
curl -X POST https://<this-proxy-host>/v1/usage-events \\
  -H "Authorization: Bearer <your_api_key>" \\
  -H "Content-Type: application/json" \\
  -d '{
    "client_call_id": "a1b2c3d4-...",
    "user_role_at_call": "engineer",
    "caller": "my-app-feature-x",
    "requested_model": "gpt-4o",
    "status": "success",
    "request_started_at": "2026-09-07T10:00:00Z"
  }'
\`\`\`

## API contract changelog
- **v1.2.0** — AI Trace Layer: Payload Capture. \`POST\`/\`GET
  /v1/trace-payloads\` — capture and read back a usage event's raw
  request/response content. Gated: requires a credential with the
  \`payloads:write\` scope AND the app's payload capture toggle enabled —
  both default OFF, contact the platform operator to turn them on.
- **v1.1.0** — AI Trace Layer. \`traces\` (create, complete, read, read
  spans) and \`tool-spans\` (record a tool-call step, with or without an
  LLM call) — correlates related usage events into one conversation and
  exposes per-call cost/token/duration breakdowns.
- **v1.0.0** — initial publication. \`usage-events\` (create, batch,
  units-generated report-back, scoped read-back), \`outcomes\` (create,
  complete), \`outcome-types\` (register, list), \`company-apps/me\`.
- **settings** — this repo's own Settings API (\`/api/control-tower/settings/*\`),
  used exclusively by the AI Control Tower React app to manage connected
  apps, credentials, and capture config. Not for external integrators.
`
  },
  servers: [
    { url: 'http://127.0.0.1:3001', description: 'Local development (this proxy)' }
    // Add the deployed ai-control-tower-proxy host here once it exists —
    // no production URL yet.
  ],
  security: [{ bearerAuth: [] }],
  tags: [
    { name: 'usage-events', description: 'Record and read back AI usage/spend events.' },
    { name: 'outcomes', description: "Create and complete outcome instances (a session's worth of related usage events)." },
    { name: 'outcome-types', description: "Register and list your app's own outcome taxonomy." },
    { name: 'traces', description: 'Correlate related usage events into one conversation/agent run.' },
    { name: 'tool-spans', description: 'Record a tool-call step, with or without an LLM call.' },
    { name: 'trace-payloads', description: "Capture and read back a usage event's raw request/response content (gated)." },
    { name: 'company-apps', description: 'Self-check on the calling credential.' },
    { name: 'settings', description: 'Internal Settings API used by the AI Control Tower React app (Supabase JWT auth, not Bearer API key).' },
    { name: 'model-pricing', description: 'Read-only global model pricing catalog (not company-scoped).' }
  ],
  // ReDoc left-nav grouping — every tag above must appear in exactly one
  // group below, or it silently disappears from the /docs nav.
  'x-tagGroups': [
    { name: 'Configuration', tags: ['settings', 'company-apps', 'model-pricing'] },
    { name: 'Usage & Traces', tags: ['usage-events', 'traces', 'tool-spans', 'trace-payloads'] },
    { name: 'Outcomes', tags: ['outcomes', 'outcome-types'] }
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        description: 'Ingestion API (/v1/*) — machine credential, SHA-256 hashed and matched against mt_company_apps.credential_hash.'
      },
      jwtAuth: {
        type: 'apiKey',
        in: 'header',
        name: 'X-Auth-Token',
        description: 'Settings API (/api/control-tower/settings/*) only — Supabase Auth access token for a human company-admin session, plus an X-Company-Id header.'
      }
    }
  }
};
