import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Check, Settings, Sparkles } from 'lucide-react';
import { getSupabase } from '../lib/supabase';
import { getEnv } from '../lib/env';
import { listCompanyApps } from '../services/controlTowerApi';
import type { CompanyApp, CompanyMembership } from '../types';
import { Card } from '../components/ui';
import { ControlTowerShell, type ShellContext } from './ControlTowerShell';

function LoginScreen({ onSignedIn }: { onSignedIn: () => void }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const { error: authError } = await getSupabase().auth.signInWithPassword({ email, password }); if (authError) throw authError; onSignedIn(); } catch (err) { setError(err instanceof Error ? err.message : 'Sign in failed.'); } finally { setBusy(false); } } return <div className="flex min-h-screen items-center justify-center p-5"><Card className="w-full max-w-md p-7"><div className="mb-7 flex items-center gap-3"><img src="/Product_Studio_Icon.ico" alt="Product Studio" className="h-11 w-11 rounded-[14px] border border-line object-contain p-1 shadow-soft" /><div><h1 className="text-[17px] font-black text-ink">AI Control Tower</h1><p className="mt-1 text-[11px] font-semibold text-muted">Standalone observability workspace</p></div></div><form onSubmit={submit} className="space-y-4"><label className="block text-[11px] font-extrabold text-text">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-control border border-line bg-soft px-3 py-3 text-[12px] outline-none" /></label><label className="block text-[11px] font-extrabold text-text">Password<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-control border border-line bg-soft px-3 py-3 text-[12px] outline-none" /></label>{error && <p className="rounded-control border border-red bg-redP px-3 py-2 text-[11px] font-bold text-red">{error}</p>}<button type="submit" disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-control border border-line bg-purple px-3 py-2 text-[11px] font-extrabold text-white shadow-soft">{busy ? 'Signing in...' : 'Sign in'}</button></form></Card></div>; }
function SetupScreen({ message }: { message: string }) { return <div className="flex min-h-screen items-center justify-center p-5"><Card className="max-w-lg p-8 text-center"><Settings className="mx-auto mb-4 text-purple" size={28} /><h1 className="text-[17px] font-black">Standalone setup required</h1><p className="mt-2 text-[12px] font-semibold leading-6 text-muted">{message}</p><p className="mt-4 rounded-control bg-soft p-3 text-left font-mono text-[11px] text-text">VITE_SUPABASE_URL=<br />VITE_SUPABASE_ANON_KEY=</p></Card></div>; }
function CompanySelection({ memberships, onSelect }: { memberships: CompanyMembership[]; onSelect: (companyId: string) => void }) { return <div className="flex min-h-screen items-center justify-center p-5"><Card className="w-full max-w-lg p-7"><h1 className="text-[17px] font-black text-ink">Choose a company</h1><p className="mt-2 text-[11px] font-semibold text-muted">Select the standalone company context for this session.</p><div className="mt-5 space-y-2">{memberships.map((membership) => <button key={membership.company_id} onClick={() => onSelect(membership.company_id)} className="flex w-full items-center justify-between rounded-control border border-line bg-white px-3 py-3 text-left text-[12px] font-extrabold text-text hover:bg-soft"><span>{membership.mt_companies?.name || 'Unnamed company'}</span><Check size={15} className="text-purple" /></button>)}</div></Card></div>; }
function LoadingScreen({ label }: { label: string }) { return <div className="flex min-h-screen items-center justify-center text-[12px] font-extrabold text-muted"><Sparkles className="mr-2 animate-pulse text-purple" size={16} />{label}</div>; }

export function Bootstrap({ children }: { children: (context: ShellContext) => React.ReactNode }) { const [configError, setConfigError] = useState(''); const [retry, setRetry] = useState(0); const [selectedCompanyId, setSelectedCompanyId] = useState<string | null>(() => localStorage.getItem('ai_control_tower_active_company_id')); useEffect(() => { try { getEnv(); } catch (error) { setConfigError(error instanceof Error ? error.message : 'Environment configuration is unavailable.'); } }, [retry]); const session = useQuery({ queryKey: ['session', retry], enabled: !configError, queryFn: async () => (await getSupabase().auth.getSession()).data.session }); const memberships = useQuery({ queryKey: ['memberships', session.data?.user.id, retry], enabled: Boolean(session.data?.user), queryFn: async () => { const { data, error } = await getSupabase().from('mt_users_companies').select('company_id, role, is_active, mt_companies(name)').eq('user_id', session.data!.user.id).eq('is_active', true); if (error) throw error; return (data ?? []) as CompanyMembership[]; } }); const membership = memberships.data?.find((item) => item.company_id === selectedCompanyId) ?? (memberships.data?.length === 1 ? memberships.data[0] : undefined); const apps = useQuery({ queryKey: ['apps', membership?.company_id], enabled: Boolean(membership?.company_id), queryFn: () => listCompanyApps(membership!.company_id) }); function selectCompany(companyId: string) { localStorage.setItem('ai_control_tower_active_company_id', companyId); setSelectedCompanyId(companyId); } if (configError) return <SetupScreen message={configError} />; if (session.isPending) return <LoadingScreen label="Checking standalone session..." />; if (!session.data) return <LoginScreen onSignedIn={() => setRetry((value) => value + 1)} />; if (memberships.isPending) return <LoadingScreen label="Loading company access..." />; if (memberships.error) return <SetupScreen message="The standalone app could not load company access. Check the Supabase policies and RPC availability." />; if (!memberships.data?.length) return <SetupScreen message="No active company membership was found for this account." />; if (!membership) return <CompanySelection memberships={memberships.data} onSelect={selectCompany} />; if (apps.isPending) return <LoadingScreen label="Loading company and app access..." />; if (apps.error) return <SetupScreen message="The standalone app could not load producer apps. Check the mt_company_apps_list RPC and Supabase policies." />; if (!apps.data?.length) return <SetupScreen message="No producer apps are available for this company." />; return children({ session: session.data, membership, apps: apps.data }); }
